### PR TITLE
Optimize

### PR DESCRIPTION
**Pull request by s1204IT**
Fixed: https://github.com/YT-Advanced/WSA-Script/pull/9#issuecomment-1526912900

### CODE REVIEW

**Comment by s1204IT** [comment]
Check Build: https://github.com/s1204IT/WSA-Script/actions/runs/4826611276/jobs/8598609663

**Comment by s1204IT** [comment]
An error occurred because "download/.ms_account" was created even when User code was not specified.

**Comment by s1204IT** [comment]
- Don't need to include `sudo` in your dependencies.
- Please keep for pip `--upgrade` option
- Please setup a Python environment using `setup-python`

**Comment by YT-Advanced** [comment]
@s1204IT Can you make an example of WSA Insider code please. Thanks

**Comment by s1204IT** [comment]
> @s1204IT Can you make an example of WSA Insider code please. Thanks

Sure, I'll do it when I've time

**Pull request merged**
