### PR TITLE
Optimize workflow

### PR DESCRIPTION
**Pull request by s1204IT**
- Use [**setup-python**](https://github.com/actions/setup-python)
  - Cache pip dependency: `requests`
- Remove dependency: `whiptail`
- Add dependency: `ca-certificates`
- Update APKs
  - **GoogleWebViewOverlay**
    - minSdk: **33**
  - **VpnDialogs** Made by [**LSPosed**](https://github.com/LSPosed/VpnDialogs)
    - minSdk: **33**
    - Signature: [Android **TestKey**](https://android.googlesource.com/platform/build/+/refs/heads/android13-platform-release/target/product/security/testkey.x509.pem)
- Grant `./script/build.sh` permission
  - 100644 -> 100**755**

### CODE REVIEW

**Comment by YT-Advanced** [comment]
@s1204IT Can you tell me what user code do ?

**Comment by YT-Advanced** [comment]
> > @s1204IT Can you tell me what user code do ?
> 
> https://github.com/LSPosed/MagiskOnWSALocal/discussions/298#discussioncomment-4441911
> It's can get releases only for MS accounts participating in WSA's preview program.
> However, getting that token is very cumbersome.

Hmm, your code have some bug so I have revert your changes

**Comment by s1204IT** [comment]
https://github.com/YT-Advanced/Test/compare/b755030...main
I didn't find any bugs other than the missing semicolon in the If.
Where exactly is the bug?

**Comment by YT-Advanced** [comment]
> [YT-Advanced/Test@b755030...main](https://github.com/YT-Advanced/Test/compare/b755030...main) I didn't find any bugs other than the missing semicolon in the If. Where exactly is the bug?

The workflow error at GetWSADownloadLink.py file Maybe it have missing something

**Pull request merged**
