### PR TITLE
Minor modify mtg

### PR DESCRIPTION
**Pull request by YT-Advanced**
Now I think we need modify this script for automatic updates: [YT-Advanced/MindTheGappsBuilder](https://github.com/YT-Advanced/MindTheGappsBuilder)

### CODE REVIEW

**Comment by s1204IT** [comment]
I'm extracting GApps from a GSI+GMS ROM.
Therefore, it seems that it is difficult to build automatically.

**Review by s1204IT — COMMENTED** [review]
Well, it's a riddle.

**Comment by s1204IT** [comment]
And then just make sure it works.
However, I can't do it now, so I'd like to ask you to verify the operation instead.

**Comment by YT-Advanced** [comment]
> I'm extracting GApps from a GSI+GMS ROM.
Therefore, it seems that it is difficult to build automatically.

Why you need to extract GApps ? We can build it !

**Comment by YT-Advanced** [comment]
> And then just make sure it works. However, I can't do it now, so I'd like to ask you to verify the operation instead.

Now I can confirm the new ones worked !

**Comment by s1204IT** [comment]
Screenshot_20230624_164735_Chrome
This just skips the compression of certain APKs from MTG and is no different than the original MTG.

Please check the zip of the one I have released to make sure it works and see what is in it.

**Comment by YT-Advanced** [comment]
@s1204IT Oh sorry, my wrong. I thought the Gapps file from you is the same with MTG. So you will mannual upload MindTheGapps, right ?

**Comment by s1204IT** [comment]
That is what I mean.

However, we have not completely removed the MTG element, so we have kept the MTG name.

**Comment by YT-Advanced** [comment]
@s1204IT But what is the benefit of the new GApps ? I think MindTheGapps is enough for us

**Comment by s1204IT** [comment]
The base APK version is out of date.

It also updates not only the APK but also the configurations.

**Comment by YT-Advanced** [comment]
@s1204IT And as I have tested, WSA failed to open :( Can you test it, the build is in Action now.

**Comment by s1204IT** [comment]
Okay,
We can close this PR.

**Comment by s1204IT** [comment]
Thanks your cooperation

**Comment by YT-Advanced** [comment]
@s1204IT Not only WSA, the WSA Manager app (Windows App) also fail to start. I don't know why, can you test it ?

**Comment by s1204IT** [comment]
Thanks your cooperation

**Comment by MustardChef** [comment]
I can confirm that WSA does not start and loads infinitely until the screen closes, although the WSA Settings app works fine.

**Comment by s1204IT** [comment]
That is evidence that Android is failing to boot.

Since the only change is MTG, this PR is  meaningless.

**Comment by YT-Advanced** [comment]
I have move permission config file to [MindTheGappsBuilder](https://github.com/YT-Advanced/MindTheGappsBuilder/) and add it to MindTheGapps output file. So I will merge this pull request

**Pull request closed without merging**
