### PR TITLE
Move config to MindTheGappsBuilder

### PR DESCRIPTION
**Pull request by YT-Advanced**
Now all custom config and GoogleWebviewOverlay are stored at [YT-Advanced/MindTheGappsBuilder](https://github.com/YT-Advanced/MindTheGappsBuilder/)

### CODE REVIEW

**Comment by YT-Advanced** [comment]
@MustardChef Can you test this build:
https://github.com/YT-Advanced/WSA-Script/actions/runs/5363890563#artifacts

**Review by s1204IT — APPROVED** [review]
The configuration itself is fine, but there is no need to run MTGBuilder with `cron`.

In `workflow_dispatch:`, run the workflow manually when the GitLab repository is updated.

**Comment by MustardChef** [comment]
@YT-Advanced Sorry for testing 8 hours after your message. Yes it works fine.

**Comment by YT-Advanced** [comment]
> @YT-Advanced Sorry for testing 8 hours after your message. Yes it works fine.

Thanks for your reply.

**Pull request merged**
