### PR TITLE
Remove `VpnDialogs` and Update 2305 documents

### LINKED ISSUE #77: [Restriction] VPN does not work.
As long as it is completely restricted on the WSA side, I don't see the need to bother rewriting VpnDialogs.

--- 
My suggestion: Remove customized `VpnDialogs`.

@YT-Advanced Please reply back whether you **agree** or **disagree** with this.

If agree, I'll get right to work.

### PR DESCRIPTION
**Pull request by s1204IT**
Close #77
### To do list
- [ ] Custom build.prop (@YT-Advanced)
- [ ] Re-add checksum in zip compression (@YT-Advanced)
- [ ] Add Insider Preview Build to Release (@YT-Advanced)
- [ ] Add MagiskOverlayFS and busybox symlink (@YT-Advanced)
- [ ] Further optimization of MindTheGapps (@s1204IT)

### CODE REVIEW

**Comment by YT-Advanced** [comment]
Keep this repos, I am going to improve the script

**Review by s1204IT — COMMENTED** [review]
https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/common/prints.sh#L65

Are there any changes that can be made by modifying the build ID?

**Comment by s1204IT** [comment]
> https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf/blob/master/common/prints.sh#L65
> 
> Are there any changes that can be made by modifying the build ID?
> 
> If changing the build ID were effective, Howard would have already implemented it. Are there any apps that will not work without even changing the build ID?

@YT-Advanced 

Originally the same build ID as Pixel 5, so there is no need to change it.

**Comment by YT-Advanced** [comment]
@s1204IT Yes, I knew. I add it because I'm going to add custom prop

**Comment by s1204IT** [comment]
I don't think we need to remove the code that changes the build ID, but if it doesn't exist, we can skip the fix arguments setting.

**Comment by s1204IT** [comment]
Since the standard is Pixel 5, it is preferable not to modify the build ID if the prop to be modified is Pixel 5.

**Comment by YT-Advanced** [comment]
I'm thinking about add build.prop to this repos then user can fork and mannually modify it. What do you think about this method ?

**Comment by s1204IT** [comment]
I am looking to add a Pixel 4a (5G) and a Pixel 5a.
Please give me your feedback on the changes I will make to the files in the next pull request.

**Comment by YT-Advanced** [comment]
@s1204IT No, I just open this pull request, and now it is not ready for merge

**Comment by s1204IT** [comment]
Please stay tuned as I make slight modifications to this pull request to restore it.

**Comment by s1204IT** [comment]
@YT-Advanced Please wait.

**Comment by YT-Advanced** [comment]
@s1204IT Oh okay

**Comment by s1204IT** [comment]
Carry over the to-do list to a new pull request.
Making both destructive and minor changes at the same time may result in unexpected behavior.

**Pull request merged**
