### PR TITLE
Support for v2306

### PR DESCRIPTION
**Pull request by s1204IT**
KernelSU : https://github.com/tiann/KernelSU/pull/704
MagiskOnWSALocal : https://github.com/LSPosed/MagiskOnWSALocal/commit/9aea5db

### CODE REVIEW

**Comment by s1204IT** [comment]
Have a issue.
```bash
if [ "$DOWN_WSA" != "no" ]; then
    python3 generateWSALinks.py "$ARCH" "$RELEASE_TYPE" "$DOWNLOAD_DIR" "$DOWNLOAD_CONF_NAME" || abort
    # shellcheck disable=SC1090
    source "$WSA_WORK_ENV" || abort
else
    printf "%s\n" "$(wget -cq -O - https://api.github.com/repos/YT-Advanced/WSAPackage/releases/latest | jq -r '.assets[] | .browser_download_url')" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
    printf "  dir=%s\n" "$DOWNLOAD_DIR" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
    printf "  out=wsa-latest.zip\n" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
    wget -P "$DOWNLOAD_DIR/xaml" "https://globalcdn.nuget.org/packages/microsoft.ui.xaml.2.8.4.nupkg"
    7z x $DOWNLOAD_DIR/xaml/*.nupkg -o../download/
    mv "$DOWNLOAD_DIR/tools/AppX/$ARCH/Release/Microsoft.UI.Xaml.2.8.appx" "$xaml_PATH"
    printf "https://aka.ms/Microsoft.VCLibs.%s.14.00.Desktop.appx\n" "$ARCH" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
    printf "  dir=%s\n" "$DOWNLOAD_DIR" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
    printf "  out=Microsoft.VCLibs.140.00.UWPDesktop_%s.appx\n" "$ARCH" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
    printf "https://cdn.glitch.global/847a3043-7118-4fd2-8853-fe9756f88702/Microsoft.VCLibs.140.00_14.0.32530.0_%s__8wekyb3d8bbwe.Appx\n" "$ARCH" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
    printf "  dir=%s\n" "$DOWNLOAD_DIR" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
    printf "  out=Microsoft.VCLibs.140.00_%s.appx\n" "$ARCH" >> "$DOWNLOAD_DIR/$DOWNLOAD_CONF_NAME" || abort
fi
```

MagiskOnWSALocal:
```bash
if [ "$DOWN_WSA" != "no" ]; then
    echo "Generate Download Links"
    python3 generateWSALinks.py "$ARCH" "$RELEASE_TYPE" "$DOWNLOAD_DIR" "$DOWNLOAD_CONF_NAME" || abort
    # shellcheck disable=SC1090
    source "$WSA_WORK_ENV" || abort
else
    WSA_MAJOR_VER=$(python3 getWSAMajorVersion.py "$ARCH" "$WSA_ZIP_PATH")
fi
```

---

In the case of "Insider Private", the major version of WSA cannot be confirmed before downloading the KernelSU.

We can also cut the file name returned in the GitHub API response with `sed` and assign it to a enviroment variable (`WSA_MAJOR_VER`).

**Comment by YT-Advanced** [comment]
I think just need to add this line to the exist code:
```bash
WSA_MAJOR_VER=$(python3 getWSAMajorVersion.py "$ARCH" "$WSA_ZIP_PATH")

**Comment by s1204IT** [comment]
> In the case of "Insider Private", the major version of WSA cannot be confirmed before downloading the KernelSU.

I suggested an alternative because of the "File not fonud" error.

**Comment by YT-Advanced** [comment]
> > In the case of "Insider Private", the major version of WSA cannot be confirmed before downloading the KernelSU.
> 
> I suggested an alternative because of the "File not fonud" error.

Now it is done

**Comment by s1204IT** [comment]
> > In the case of "Insider Private", the major version of WSA cannot be confirmed before downloading the KernelSU.
> 
> I suggested an alternative because of the "File not fonud" error.

```Py
Traceback (most recent call last):
  File "/home/runner/work/WSA-Script/WSA-Script/scripts/getWSAMajorVersion.py", line 31, in <module>
    with zipfile.ZipFile(wsa_zip_path) as zip:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/zipfile.py", line 1284, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../download/wsa-latest.zip'
```

This is what I wanted to convey.

**Comment by YT-Advanced** [comment]
@s1204IT Fixed it !

**Comment by YT-Advanced** [comment]
Moved to new branch !

**Pull request closed without merging**
