### PR TITLE
Reflect Win11 Release channel Terminology

### PR DESCRIPTION
**Pull request by BraINstinct0**
[Win 11 Terminology](https://blogs.windows.com/windows-insider/2020/06/15/introducing-windows-insider-channels/) for release channels are:
```
Fast ring == Dev Channel
Slow ring == Beta Channel
Release Preview ring == Release Preview Channel
```
Included these terms in parentheses.

### CODE REVIEW

**Comment by BraINstinct0** [comment]
Besides, before merging/closing this PR - what exactly is an **Insider Private** channel? Does it refer to the `Skip Ahead` Ring, which was essentially the faster-than-fast ring?
If so, I'm not sure how it should be renamed or handled, since [Skip Ahead was essentially killed off](https://blogs.windows.com/windows-insider/2019/11/05/announcing-windows-10-insider-preview-build-19018/) off.
Even more problematic is, [Now windows 11 release channel is Canary, Dev, Beta, and RP](https://blogs.windows.com/windows-insider/2023/03/06/whats-coming-for-the-windows-insider-program-in-2023/) which does not match exactly with the Windows 10 Release channel naming convention.
 However if there's another invite-only (aka Private) release channel active, I'd be happy to learn about it

**Comment by BraINstinct0** [comment]
If, instead, anyone provides how the original `latest` channel was decided (any docs would suffice) I'll try to figure out how best to match Win10 and Win11 release channel terminologies.

**Comment by YT-Advanced** [comment]
> Besides, before merging/closing this PR - what exactly is an **Insider Private** channel? Does it refer to the `Skip Ahead` Ring, which was essentially the faster-than-fast ring?
> If so, I'm not sure how it should be renamed or handled, since [Skip Ahead was essentially killed off](https://blogs.windows.com/windows-insider/2019/11/05/announcing-windows-10-insider-preview-build-19018/) off.
> Even more problematic is, [Now windows 11 release channel is Canary, Dev, Beta, and RP](https://blogs.windows.com/windows-insider/2023/03/06/whats-coming-for-the-windows-insider-program-in-2023/) which does not match exactly with the Windows 10 Release channel naming convention.
>  However if there's another invite-only (aka Private) release channel active, I'd be happy to learn about it

Insider Private is a channel that only user who registered to Insider Program can get access to

**Comment by BraINstinct0** [comment]
Sorry to bother (again), but all four channels (Canary, Dev, Beta and RP) require registering to the Insider Program.
Or was it meant for the `WSA Preview` program? In that case, I'd suppose using `WSA Preview` would be less confusing, as the other three (apart from Retail) are for WIndows release channels.

**Comment by YT-Advanced** [comment]
Yes, I meant WSA Preview Program. Sometime, Microsoft didn't release any version in Dev Channel so we must mannual upload WSA to Github for building

**Comment by BraINstinct0** [comment]
OK then I think changing the title from Insider Private to WSA Insider would be clearer. Would it do?

**Comment by YT-Advanced** [comment]
Yes

**Pull request merged**
