### PR TITLE
Reducing build time

### PR DESCRIPTION
**Pull request by s1204IT**

### CODE REVIEW

**Comment by YT-Advanced** [comment]
For Auto Build, should we use Artifact instead of Cache ?
We have problem that if run Auto Build, all old cache will be deleted and the Auto Build may not work correctly
Also it will clean all old cache include apt ones

**Comment by s1204IT** [comment]
I think one way would be to do automatic builds in another repository and release to this repository.
Problems with caches exceeding 10GB can be resolved by either removing the NoGApps variant or by allowing time for each architecture.

**Comment by YT-Advanced** [comment]
> I think one way would be to do automatic builds in another repository and release to this repository. Problems with caches exceeding 10GB can be resolved by either removing the NoGApps variant or by allowing time for each architecture.

I think use Artifact is the best way

**Comment by s1204IT** [comment]
> I think use Artifact is the best way

But what about build time?

**Comment by s1204IT** [comment]
There are a lot of conflicts, so I merged it into another PR(#721).

**Pull request closed without merging**
