### PR TITLE
Update auto-build workflow

### LINKED ISSUE #566: [Bug] Write-Error: Some files are missing since the last few releases
### Steps to reproduce

1. Extract the archive 
2. Run the run.bat file

### Expected behaviour

Should install WSA 

### Actual behaviour

This error occurs:
pwsh_87pW47YwAs

### Windows version

win 11 22H2

### Build Issue number

2308.40000.3.0

### Version requirement

- [X] I am using latest commit of WSA-Script commit

### LINKED ISSUE #622: [Bug] Short description.
### Steps to reproduce

1. 'run.bat' running error
2. SHA-256 value is correct
3. WSA_2309.40000.2.0_x64_Release-Nightly-with-Magisk-26.3-stable-MindTheGapps-13.0-as-Pixel-5-RemovedAmazon

### Expected behaviour

1

### Actual behaviour

[](url)
屏幕截图 2023-09-29 162138

### Windows version

win 11

### Build Issue number

_No response_

### Version requirement

- [X] I am using latest commit of WSA-Script commit

### PR DESCRIPTION
**Pull request by s1204IT**
Close #566
Close #622

### CODE REVIEW

**Comment by YT-Advanced** [comment]
You reproduced the issues successfully ?

**Comment by s1204IT** [comment]
No, this pull request was just an optimization xD

This is because the "apex" directory of "-RemovedAmazon" was empty and was ignored by `upload-artifact`.

**Comment by s1204IT** [comment]
https://github.com/YT-Advanced/WSA-Script/commit/ad16a75#diff-3d64996115d0ac3b74e36f57ce6b00d6b4982614c41b1ed39eab8ef43b2e9a2bL804

**Comment by s1204IT** [comment]
Resolved the problem of missing files and the problem with MakePri.
This is really the solution

**Pull request merged**
