### PR TITLE
Support v2306

### PR DESCRIPTION
**Pull request by YT-Advanced**
- Add support for mounting EXT4 image
- Add KernelSU version

### CODE REVIEW

**Comment by YT-Advanced** [comment]
@s1204IT Can you test the build ?

**Comment by s1204IT** [comment]
> @s1204IT Can you test the build ?

I will test it as soon as the PR for KernelSU is merged.

**Comment by YT-Advanced** [comment]
I think we can merge now!

**Comment by s1204IT** [comment]
> I think we can merge now!


The crucial WSA kernel has not yet been released.

**Review by s1204IT — APPROVED** [review]

**Comment by s1204IT** [comment]
`WSA_MAJOR_VER` is not at its normal value.

**Comment by YT-Advanced** [comment]
@s1204IT Oh, I see. This error occurs because the KernelSU generate download link first, then download WSA and get `WSA_MAJOR_VER`.

**Comment by s1204IT** [comment]
Why did you revert?
At the time you make your changes, the WSA package has not yet been downloaded, so you will not get the major version.

**Comment by YT-Advanced** [comment]
@s1204IT Oh, my wrong. But I think we have better way to do this.

**Comment by s1204IT** [comment]
> we have better way to do this.
That is true, but this is a temporary workaround.
It also has little effect on build time.

**Review by s1204IT — APPROVED** [review]

**Comment by s1204IT** [comment]
Now all we have to do is wait for the release with KernelSU.

**Comment by s1204IT** [comment]
If you are going to download the files first anyway, we recommend that you download them in `aria2c` in bulk.

If you don't want to do that, `curl` is recommended.

**Comment by s1204IT** [comment]
@YT-Advanced 
Please continue in the "v2306-optimize" branch.

**Comment by YT-Advanced** [comment]
@s1204IT If we use `curl`, we must cd to path, which is not recommended for this script. I think wget is better.

**Comment by s1204IT** [comment]
> @s1204IT If we use `curl`, we must cd to path, which is not recommended for this script. I think wget is better.

Why is it necessary to use `cd`?
There is no need.
Relative paths can be used.

**Comment by s1204IT** [comment]
Fundamentally, I think it is just a matter of downloading everything together in `aria2c`.

**Comment by YT-Advanced** [comment]
@s1204IT I think aria2c is enough

**Comment by s1204IT** [comment]
> @s1204IT I think aria2c is enough

Yes.
So, do you keep your current (616fc22) commit?

**Comment by YT-Advanced** [comment]
@s1204IT Merge now ?

**Comment by s1204IT** [comment]
We'll consider this optimization another time.

**Pull request merged**
