### PR TITLE
Custom build.prop

### PR DESCRIPTION
**Pull request by YT-Advanced**

### CODE REVIEW

**Review by s1204IT — COMMENTED** [review]
Since it is a quandary to change the WSA version each time, it would be more reliable and easier to copy the build.prop from all system partitions and rewrite specific parts with the sed command.

**Comment by YT-Advanced** [comment]
@s1204IT I knew. So when --custom-prop is not specific, it will copy the build.prop from WSA and push to Github

**Comment by s1204IT** [comment]
Please wait until I've completed my work as it'll conflict with my branch.

**Comment by s1204IT** [comment]
Question before resolve the conflict, is the `--custom-prop` option mandatory?

**Comment by YT-Advanced** [comment]
No, you can close it

**Pull request closed without merging**
